//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opciones_tecnologia
    {
        public int id_opcion { get; set; }
        public int tipo_tecnologia_id { get; set; }
        public int orden_id { get; set; }
        public string descripcion { get; set; }
    
        public virtual tipo_tecnologia tipo_tecnologia { get; set; }
        public virtual tipo_tecnologia tipo_tecnologia1 { get; set; }
    }
}
