//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_tecnologia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_tecnologia()
        {
            this.opciones_tecnologia = new HashSet<opciones_tecnologia>();
            this.opciones_tecnologia1 = new HashSet<opciones_tecnologia>();
        }
    
        public int id_tipo_tecnologia { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opciones_tecnologia> opciones_tecnologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opciones_tecnologia> opciones_tecnologia1 { get; set; }
    }
}
